# Generated by Django 5.1.2 on 2024-10-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('completed', 'Tamomlangan'), ('canceled', 'Bekor qilingan')], default='pending', max_length=20),
        ),
    ]
